swiftmailer:
    default_mailer: instant_mailer
    mailers:
        instant_mailer:
            url: '%env(MAILER_URL)%'
            spool: { type: 'memory' }
        queue_mailer:
            url: '%env(MAILER_URL)%'
            spool: { type: 'file' }
