version: '3'
services:
    rekrutacja-web:
        build: ./docker/web
        container_name: rekrutacja-web
        ports:
            - 80:80
        volumes:
            - ".:/var/www/html:rw"
            - "./docker/web/apache-config.conf:/etc/apache2/sites-enabled/000-default.conf:ro"
        links:
            - rekrutacja-mysql

    rekrutacja-mysql:
        image: vsamov/mysql-5.1.73
        container_name: rekrutacja-mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=rekrutacja
            - MYSQL_DATABASE=rekrutacja
            - MYSQL_USER=rekrutacja
            - MYSQL_PASSWORD=rekrutacja
