App\Entity\Post:
    properties:
        ordinal:
            - NotBlank:
                message: Liczba porządkowa nie może być pusta
            - GreaterThanOrEqual:
                value: 1
                message: Liczba porządkowa musi być dodatnią liczbą naturalną
        topic:
            - NotBlank:
                message: Temat nie może być pusty
            - Length:
                max: 255
                maxMessage: Temat nie może być dłuższy, niż 255 znaków
        content:
            - NotBlank:
                message: Treść nie może być pusta
        active:
            - Type:
                type: bool
                message: Pole active musi być wartością logiczną

App\Entity\Subscriber:
    properties:
        first_name:
            - NotBlank:
                message: Imię nie może być puste
            - Length:
                max: 255
                maxMessage: Imię nie może być dłuższe, niż 255 znaków
        surname:
            - NotBlank:
                message: Nazwisko nie może być puste
            - Length:
                max: 255
                maxMessage: Nazwisko nie może być dłuższe, niż 255 znaków
        email:
            - NotBlank:
                message: Email nie może być pusty
            - Email:
                message: Email nie jest poprawny
        school:
            - NotBlank:
                message: Szkoła musi zostać uzupełnona

App\Entity\School:
    properties:
        name:
            - NotBlank:
                message: Nazwa szkoły nie może być pusta
            - Length:
                max: 255
                maxMessage: Nazwa szkoły nie może być dłuższa, niż 255 znaków
        accepted:
            - Type:
                type: bool
                message: Pole accepted musi być wartością logiczną
