api_post_show_all:
    path: /posts
    controller: App\Controller\PostController::showAll
    methods: [GET]

api_post_show_one:
    path: /posts/{id}
    controller: App\Controller\PostController::showOne
    methods: [GET]
    requirements:
        id: '\d+'

api_post_add:
    path: /posts
    controller: App\Controller\PostController::add
    methods: [POST]

api_post_update:
    path: /posts/{id}
    controller: App\Controller\PostController::update
    methods: [PUT]
    requirements:
        id: '\d+'

api_post_delete:
    path: /posts/{id}
    controller: App\Controller\PostController::delete
    methods: [DELETE]
    requirements:
        id: '\d+'


api_subscriber_show_all:
    path: /subscribers
    controller: App\Controller\SubscriberController::showAll
    methods: [GET]

api_subscriber_show_one:
    path: /subscribers/{id}
    controller: App\Controller\SubscriberController::showOne
    methods: [GET]
    requirements:
        id: '\d+'

api_subscriber_add:
    path: /subscribers
    controller: App\Controller\SubscriberController::add
    methods: [POST]


api_school_show_all:
    path: /schools
    controller: App\Controller\SchoolController::showAll
    methods: [GET]

api_school_show_one:
    path: /schools/{id}
    controller: App\Controller\SchoolController::showOne
    methods: [GET]

api_school_add:
    path: /schools
    controller: App\Controller\SchoolController::add
    methods: [POST]

api_school_update:
    path: /schools/{id}
    controller: App\Controller\SchoolController::update
    methods: [PUT]

api_school_delete:
    path: /schools/{id}
    controller: App\Controller\SchoolController::delete
    methods: [DELETE]

api_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: [POST]
